KafkaServer {
  org.apache.kafka.common.security.scram.ScramLoginModule required
    username="admin"
    password="uosieQu6ACie0eichoo5ohdeeWaepowa";
  org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="uosieQu6ACie0eichoo5ohdeeWaepowa"
    user_admin="uosieQu6ACie0eichoo5ohdeeWaepowa";
    user_producer="producer"
    user_consumer="consumer";
};